services:
  postgres:
    container_name: postgres
    image: postgres-contrib
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trigram
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
