name: bachelor

services:
  postgres:
    container_name: postgres
    image: postgres-contrib
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env

  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:latest
    environment:
      MEILI_MASTER_KEY: ${MEILI_KEY}
    ports:
      - 7700:7700
    volumes:
      - meili:/meili_data
    env_file:
      - .env

volumes:
  postgres:
  meili:
