services:
  postgres:
    container_name: postgres
    image: postgres-contrib
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trigram
    volumes:
      - postgres:/var/lib/postgresql/data

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    environment:
      MEILI_MASTER_KEY: "y9iPmYwIjjm6uqLZ9SejDViU6SbkfufLZTfuffufMzfPJM"
    ports:
      - "7700:7700"
    volumes:
      - ./data:/meili_data

volumes:
  postgres:
