name: bachelor

services:
  postgres:
    container_name: bachelor-postgres
    image: postgres-contrib
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env

  meilisearch:
    container_name: bachelor-meilisearch
    image: getmeili/meilisearch:latest
    environment:
      MEILI_MASTER_KEY: ${MEILI_KEY}
    ports:
      - "7700:7700"
    volumes:
      - meili:/meili_data
    env_file:
      - .env

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    network_mode: host
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro
    privileged: true

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    network_mode: host
    ports:
      - "9090:9090"
    volumes:
      - "./conf/prometheus.yml:/etc/prometheus/prometheus.yml"
    depends_on:
      - cadvisor

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    network_mode: host
    ports:
      - "3000:3000"
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - DS_PROMETHEUS=prometheus
    volumes:
      - "grafana:/var/lib/grafana"
      - "./conf/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml"
      - "./conf/dashboard.json:/var/lib/grafana/dashboards/dashboard.json"
      - "./conf/default.yml:/etc/grafana/provisioning/dashboards/default.yml"
    depends_on:
      - prometheus

volumes:
  postgres:
  meili:
  grafana:
