name: bachelor

services:
  meilisearch:
    container_name: bachelor-meilisearch
    image: getmeili/meilisearch:latest
    environment:
      MEILI_MASTER_KEY: ${MEILI_KEY}
    ports:
      - "7700:7700"
    volumes:
      - meili:/meili_data

volumes:
  meili:
