global:
  scrape_interval: 1s

scrape_configs:
  - job_name: "cadvisor"
    static_configs:
      - targets: ["localhost:8080"]

  - job_name: "nvidia_smi"
    static_configs:
      - targets: ["localhost:9835"]
