@startuml db-schema

skinparam dpi 300

object documents {
  + id: uuid
  + title: varchar[255]
}

object document_parts {
  + id: uuid
  + document_id: uuid
  + content: text
}

documents <-- document_parts

@enduml
